In [1]:
import pandas as pd
import numpy as np
import geo_process as gp
import preprocess_data as pp

In [2]:
# Maximum capacity of Santa's sleigh is 10 tonnes = 10,000 kg = 10,000,000 g
max_load_g = 1e7

In [3]:
nice_raw = pp.read_input()

In [4]:
nice_raw.head()

ID    lat_deg    lon_deg      wt
0  -1  68.073611  29.315278       0
1   2  40.733034 -86.762233  342917
2   3  43.029635 -91.094895  974703
3   4  31.180215  16.596037  215099
4   5 -28.657398 -55.964951  568144

In [5]:
nice_raw.iloc[1:, :].describe()

ID       lat_deg       lon_deg            wt
count  10000.00000  10000.000000  10000.000000  1.000000e+04
mean    5001.50000     27.720125    -17.268937  5.308228e+05
std     2886.89568     24.241659     78.886361  4.291983e+05
min        2.00000    -90.000000   -179.593071  5.000000e+00
25%     2501.75000     14.431097    -85.826239  2.514975e+05
50%     5001.50000     36.169634    -40.346728  5.027195e+05
75%     7501.25000     42.718775     34.304132  7.563300e+05
max    10001.00000     90.000000    179.385081  9.158430e+06

In [103]:
nice_data = gp.calc_trigs(nice_raw, lat_col='lat_deg', lon_col='lon_deg')
nice_data = gp.calc_cartesian(nice_data)

In [7]:
nice_data.head()

ID    lat_deg    lon_deg      wt   lon_sin   lat_sin   lon_cos   lat_cos
0  -1  68.073611  29.315278       0  0.489615  0.927664  0.871939  0.373415
1   2  40.733034 -86.762233  342917 -0.998404  0.652535  0.056480  0.757758
2   3  43.029635 -91.094895  974703 -0.999817  0.682377 -0.019108  0.731001
3   4  31.180215  16.596037  215099  0.285622  0.517732  0.958342  0.855543
4   5 -28.657398 -55.964951  568144 -0.828695 -0.479571  0.559700  0.877503

In [8]:
ef_dist = gp.r_earth*np.array([gp.calc_gca(nice_data, row1=0, row2=ind) for ind in range(1,nice_data.shape[0])])
    

In [9]:
pd.Series(ef_dist).hist()

In [10]:
#dist_mat_100 = gp.dist_mat(nice_data.head(100))

In [11]:
# How many presents, on average, fits into a load
max_load_g/nice_data.wt.iloc[1:,].mean()

18.838680114838816

In [12]:
# How many trips, ideally, would be needed
nice_data.wt.iloc[1:,].sum()/max_load_g

530.8227508

In [13]:
nice_data.wt.iloc[[]].values.sum()

0

In [14]:
weights = nice_data.wt.iloc[1:,].values.copy()
weights.sort()

In [15]:
weights

array([      5,      91,     215, ..., 4930630, 4952381, 9158430])

In [16]:
nice_data[nice_data.wt > 4e6]

ID    lat_deg     lon_deg       wt   lon_sin   lat_sin   lon_cos  \
303    304  46.219734 -119.883858  4575070 -0.867037  0.721999 -0.498243   
607    608  41.130244  -81.876773  4139851 -0.989966  0.657773  0.141303   
683    684  18.214623  -72.522091  4622316 -0.953833  0.312577  0.300338   
1063  1064  44.665820   21.639493  4499156  0.368765  0.702971  0.929523   
1215  1216  42.621039  -70.680065  4788802 -0.943686  0.677146  0.330843   
1443  1444  47.489667  134.751043  4930630  0.710173  0.737155 -0.704028   
1519  1520  42.096631   19.545595  4282474  0.334557  0.670383  0.942376   
1671  1672  51.611699   -0.204734  4726551 -0.003573  0.783820  0.999994   
2203  2204  26.274659  105.930249  4783677  0.961597  0.442675 -0.274467   
2297  2298   2.106498   31.400424  9158430  0.521016  0.036757  0.853547   
2431  2432  47.221853    9.513367  4535504  0.165278  0.733989  0.986247   
2583  2584  41.614367   24.691934  4123131  0.417739  0.664114  0.908567   
2735  2736  -3.787457  119.641860  4502295  0.869134 -0.066055 -0.494577   
2887  2888  22.683236  120.457719  4442118  0.862003  0.385636 -0.506902   
3495  3496  22.370548 -102.839259  4681142 -0.974997  0.380595 -0.222217   
3723  3724  39.688147  -78.899404  4865396 -0.981291  0.638609  0.192532   
3799  3800  57.991264  102.626953  4220811  0.975814  0.847967 -0.218602   
3875  3876  55.751208  -97.878777  4864102 -0.990560  0.826602 -0.137078   
4407  4408  41.535105  -81.581461  4191482 -0.989225  0.663079  0.146403   
4635  4636  26.054728  119.306369  4730505  0.872015  0.439229 -0.489479   
5243  5244  57.472926   60.234211  4796649  0.868062  0.843137  0.496456   
5319  5320  48.985168   14.443324  4850558  0.249422  0.754540  0.968395   
5623  5624  39.492713 -121.549609  4150041 -0.852187  0.635980 -0.523237   
5775  5776 -25.896607   25.629273  4172638  0.432546 -0.436749  0.901612   
5927  5928  37.444848  116.316048  4245578  0.896362  0.607997 -0.443322   
6003  6004  40.447609  -79.959868  4447628 -0.984686  0.648752  0.174338   
6459  6460  37.379905 -118.366415  4238660 -0.879927  0.607097 -0.475109   
6763  6764  42.944793  -85.332707  4543425 -0.996684  0.681293  0.081370   
7219  7220  24.867927 -103.709595  4860183 -0.971509  0.420528 -0.237001   
8055  8056  43.714255 -116.382156  4952381 -0.895850  0.691062 -0.444356   
8283  8284  34.785989   -5.547797  4435343 -0.096676  0.570513  0.995316   
8587  8588  49.513159   57.461618  4056879  0.843031  0.760555  0.537864   
8663  8664   9.335220  -82.262362  4713604 -0.990895  0.162210  0.134637   
9043  9044  41.849494  -89.481462  4533081 -0.999959  0.667176  0.009050   
9423  9424  36.269975    2.831717  4593920  0.049403  0.591591  0.998779   
9651  9652  65.703878  -18.098139  4526995 -0.310646  0.911431  0.950526   
9727  9728  44.897798  -74.897102  4805919 -0.965459  0.705844  0.260553   
9803  9804 -24.832021   16.967961  4517800  0.291837 -0.419959  0.956468   

       lat_cos  
303   0.691895  
607   0.753216  
683   0.949892  
1063  0.711219  
1215  0.735848  
1443  0.675723  
1519  0.742015  
1671  0.620988  
2203  0.896682  
2297  0.999324  
2431  0.679161  
2583  0.747632  
2735  0.997816  
2887  0.922651  
3495  0.924742  
3723  0.769532  
3799  0.530049  
3875  0.562788  
4407  0.748550  
4635  0.898375  
5243  0.537698  
5319  0.656254  
5623  0.771705  
5775  0.899584  
5927  0.793939  
6003  0.760999  
6459  0.794628  
6763  0.732010  
7219  0.907280  
8055  0.722795  
8283  0.821289  
8587  0.649273  
8663  0.986756  
9043  0.744900  
9423  0.806238  
9651  0.411453  
9727  0.708367  
9803  0.907543

In [17]:
nice_weights = nice_data['wt'].iloc[1:].sort_values(ascending=False)

In [18]:
min(nice_weights.index.values)

1

In [19]:
nice_data['wt'].iloc[10000]

663913

In [20]:
nice_weights.iloc[2297]

777817

In [21]:
nice_weights.index.values[0]

2297

In [22]:
nice_data['wt'].loc[2297]

9158430

## Try out simulated annealing

In [79]:
nice_data_test = pd.concat([nice_data.head(1), nice_data.iloc[1:,].sample(20)])

In [80]:
nice_data_test

ID    lat_deg     lon_deg      wt   lon_sin   lat_sin   lon_cos  \
0       -1  68.073611   29.315278       0  0.489615  0.927664  0.871939   
9585  9586  56.343668   21.052687  400673  0.359226  0.832377  0.933250   
394    395  47.256115   28.312335  315100  0.474278  0.734395  0.880375   
5968  5969  26.537769  101.702922  568533  0.979212  0.446788 -0.202837   
5834  5835  41.432354  -81.534618  711347 -0.989105  0.661735  0.147212   
5737  5738 -20.687946  -46.601841  667596 -0.726597 -0.353278  0.687064   
5352  5353  39.048166  -94.290948  141064 -0.997197  0.629973 -0.074821   
5746  5747 -27.172731  151.241777  310042  0.481115 -0.456675 -0.876658   
7605  7606  35.498596  -97.971420  185664 -0.990337  0.580683 -0.138679   
2338  2339  25.132601  121.728394  331821  0.850551  0.424715 -0.525893   
3412  3413  42.477381  -75.045173  709246 -0.966130  0.675299  0.258057   
3301  3302  37.388267 -122.168566  452083 -0.846485  0.607213 -0.532412   
3568  3569  31.625841  -97.101147  739065 -0.992329  0.524370 -0.123621   
2482  2483  36.267447    1.963688  156769  0.034266  0.591555  0.999413   
261    262  34.664851   50.909482  924326  0.776151  0.568775  0.630547   
801    802  25.426723   30.560872  499167  0.508453  0.429356  0.861089   
6421  6422  37.688605  112.716875  555595  0.922424  0.611370 -0.386178   
589    590  57.774135   25.999987  197945  0.438371  0.845953  0.898794   
3150  3151  40.144664  -88.956888  673807 -0.999834  0.644720  0.018205   
1277  1278  39.519374  -76.170529  276055 -0.971011  0.636339  0.239033   
7404  7405   2.675210  -75.318212  273779 -0.967348  0.046674  0.253450   

       lat_cos  
0     0.373415  
9585  0.554210  
394   0.678722  
5968  0.894640  
5834  0.749738  
5737  0.935518  
5352  0.776617  
5746  0.889634  
7605  0.814130  
2338  0.905327  
3412  0.737544  
3301  0.794539  
3568  0.851491  
2482  0.806265  
261   0.822493  
801   0.903135  
6421  0.791345  
589   0.533258  
3150  0.764419  
1277  0.771409  
7404  0.998910

In [81]:
dist_mat_test = gp.dist_mat(nice_data_test, gca_fun=gp.calc_gca)

In [82]:
dist_mat_test.shape

(20, 21)

In [31]:
import logging

In [32]:
loglevel = logging.DEBUG
logging.basicConfig(format='%(asctime)s %(levelname)s:%(message)s', level=loglevel, datefmt='%Y-%m-%d %H:%M:%S')


In [83]:
nice_data_test = nice_data_test.reset_index()

In [84]:
initial_route_order = nice_data_test.iloc[1:, ].index.values

In [85]:
initial_route_order

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [86]:
from single_route_anneal import SingleSantaProblem
ssp = SingleSantaProblem(initial_route_order, dist_mat_test)
ssp.Tmax = 50
ssp.Tmin = 0.1
ssp.steps = 20000

In [87]:
route, route_len = ssp.anneal()

 Temperature        Energy    Accept   Improve     Elapsed   Remaining
     0.10000         11.32     6.00%     1.50%     0:00:02     0:00:00

In [88]:
route
list(list(route))

[17, 16, 9, 7, 3, 14, 15, 2, 13, 5, 20, 19, 10, 4, 6, 8, 11, 12, 18, 1]

In [89]:
nice_data_test.iloc[[0] + list(route) + [0],]

index    ID    lat_deg     lon_deg      wt   lon_sin   lat_sin   lon_cos  \
0       0    -1  68.073611   29.315278       0  0.489615  0.927664  0.871939   
17    589   590  57.774135   25.999987  197945  0.438371  0.845953  0.898794   
16   6421  6422  37.688605  112.716875  555595  0.922424  0.611370 -0.386178   
9    2338  2339  25.132601  121.728394  331821  0.850551  0.424715 -0.525893   
7    5746  5747 -27.172731  151.241777  310042  0.481115 -0.456675 -0.876658   
3    5968  5969  26.537769  101.702922  568533  0.979212  0.446788 -0.202837   
14    261   262  34.664851   50.909482  924326  0.776151  0.568775  0.630547   
15    801   802  25.426723   30.560872  499167  0.508453  0.429356  0.861089   
2     394   395  47.256115   28.312335  315100  0.474278  0.734395  0.880375   
13   2482  2483  36.267447    1.963688  156769  0.034266  0.591555  0.999413   
5    5737  5738 -20.687946  -46.601841  667596 -0.726597 -0.353278  0.687064   
20   7404  7405   2.675210  -75.318212  273779 -0.967348  0.046674  0.253450   
19   1277  1278  39.519374  -76.170529  276055 -0.971011  0.636339  0.239033   
10   3412  3413  42.477381  -75.045173  709246 -0.966130  0.675299  0.258057   
4    5834  5835  41.432354  -81.534618  711347 -0.989105  0.661735  0.147212   
6    5352  5353  39.048166  -94.290948  141064 -0.997197  0.629973 -0.074821   
8    7605  7606  35.498596  -97.971420  185664 -0.990337  0.580683 -0.138679   
11   3301  3302  37.388267 -122.168566  452083 -0.846485  0.607213 -0.532412   
12   3568  3569  31.625841  -97.101147  739065 -0.992329  0.524370 -0.123621   
18   3150  3151  40.144664  -88.956888  673807 -0.999834  0.644720  0.018205   
1    9585  9586  56.343668   21.052687  400673  0.359226  0.832377  0.933250   
0       0    -1  68.073611   29.315278       0  0.489615  0.927664  0.871939   

     lat_cos  
0   0.373415  
17  0.533258  
16  0.791345  
9   0.905327  
7   0.889634  
3   0.894640  
14  0.822493  
15  0.903135  
2   0.678722  
13  0.806265  
5   0.935518  
20  0.998910  
19  0.771409  
10  0.737544  
4   0.749738  
6   0.776617  
8   0.814130  
11  0.794539  
12  0.851491  
18  0.764419  
1   0.554210  
0   0.373415

In [77]:
import geojson

def format_route_to_geojson(nice_data, route, filename='route.geojson'):
    full_route = [0] + list(route) + [0]
    coord_DF = nice_data[['lat_deg', 'lon_deg']].iloc[full_route,]
    
    coord_tuples = [(coord_DF['lon_deg'].iloc[ind,], coord_DF['lat_deg'].iloc[ind,])
                    for ind in range(coord_DF.shape[0])]
    
    line_segments = geojson.LineString(coord_tuples)
    
    with open(filename, 'w') as f:
        geojson.dump(line_segments, f)

In [90]:
format_route_to_geojson(nice_data_test, route)

In [91]:
print(list((0, 1)).__doc__)

list() -> new empty list
list(iterable) -> new list initialized from iterable's items


In [92]:
foolist = list((0, 1))

In [93]:
foolist

[0, 1]

In [95]:
print(foolist.sort.__doc__)

L.sort(key=None, reverse=False) -> None -- stable sort *IN PLACE*


In [98]:
import sklearn.cluster as clust

In [117]:
num_clust = 540
knn_clust = clust.KMeans(n_clusters=num_clust, copy_x=True)
agg_clust = clust.AgglomerativeClustering(n_clusters=num_clust, linkage='ward')

In [131]:
knn_clust.fit(nice_data[['x', 'y', 'z']])
clusters_knn = knn_clust.predict(nice_data[['x', 'y', 'z']])
#clusters = agg_clust.fit_predict()

In [119]:
type(clusters)

numpy.ndarray

In [120]:
clusters.shape

(10001,)

In [122]:
clusters[:5]

array([ 70, 422,  12, 112,  60])

In [124]:
cluster_labels = list(set(clusters))
cluster_labels.sort()
cluster_labels[:5] + cluster_labels[-5:]

[0, 1, 2, 3, 4, 535, 536, 537, 538, 539]

In [125]:
pd.Series(clusters).value_counts()

182    203
460    186
481    123
318    121
458    106
135    100
159     93
373     89
46      88
224     84
111     82
24      82
379     77
195     72
10      69
256     68
445     68
268     68
338     67
22      63
430     63
41      63
37      62
7       61
442     59
12      59
518     58
40      57
372     57
260     55
      ... 
534      3
509      3
345      3
497      3
521      3
515      3
436      3
352      3
99       3
179      3
132      3
374      3
359      2
369      2
273      2
495      2
433      2
376      2
360      2
536      1
393      1
485      1
307      1
333      1
306      1
346      1
399      1
423      1
511      1
315      1
Length: 540, dtype: int64

In [154]:
cluster_matches_single = np.where(clusters == cluster_labels[260])[0]
print(nice_data.iloc[cluster_matches_single,].wt.sum()/1e7)
nice_data.iloc[cluster_matches_single,].head(10)

2.8884171


ID    lat_deg    lon_deg      wt   lon_sin   lat_sin   lon_cos  \
245    246  46.044400  20.029888  912658  0.342510  0.719878  0.939514   
595    596  45.937077  20.058650  863390  0.342982  0.718576  0.939342   
756    757  45.339675  19.588895  848675  0.335269  0.711286  0.942122   
859    860  45.532558  19.785463  334980  0.338499  0.713649  0.940967   
913    914  45.363762  20.390159  259197  0.348411  0.711582  0.937342   
1068  1069  45.587109  19.669270  645708  0.336590  0.714315  0.941651   
1254  1255  45.795078  19.082648   87160  0.326932  0.716851  0.945048   
1619  1620  45.200213  20.303360  862588  0.346991  0.709573  0.937869   
1625  1626  45.125956  19.222626  321231  0.329240  0.708660  0.944246   
1935  1936  45.570905  18.679259  542321  0.320270  0.714117  0.947326   

       lat_cos         x         y         z  
245   0.694101  0.652117  0.237737  0.719878  
595   0.695448  0.653263  0.238526  0.718576  
756   0.702902  0.662220  0.235661  0.711286  
859   0.700504  0.659151  0.237120  0.713649  
913   0.702603  0.658579  0.244795  0.711582  
1068  0.699824  0.658990  0.235554  0.714315  
1254  0.697227  0.658913  0.227946  0.716851  
1619  0.704632  0.660852  0.244501  0.709573  
1625  0.705551  0.666214  0.232295  0.708660  
1935  0.700026  0.663153  0.224197  0.714117

ID   lat_deg    lon_deg  wt   lon_sin   lat_sin   lon_cos   lat_cos  \
4443  4444 -37.06778 -12.310697   5 -0.213213 -0.602759  0.977006  0.797923   

             x         y         z  
4443  0.779575 -0.170127 -0.602759

In [134]:
knn_clust.cluster_centers_

array([[ 0.78561854, -0.05832553,  0.61514839],
       [ 0.05858529, -0.73870165,  0.67129881],
       [-0.36661652,  0.84490117,  0.38926638],
       ...,
       [ 0.34130553,  0.45903   ,  0.81995818],
       [ 0.12131484,  0.87342385,  0.47121117],
       [ 0.2467625 , -0.67693127,  0.69329625]])

In [156]:
min(knn_clust.cluster_centers_[:, 0]**2 + knn_clust.cluster_centers_[:, 1]**2 + knn_clust.cluster_centers_[:,2]**2)

0.9957014533473346

In [158]:
any([True])

True

In [166]:
nice_data.head(2)[['x', 'y', 'z']].values.shape

(2, 3)

In [167]:
foolist

[0, 1]

In [168]:
foolist[2] = 55

IndexError: list assignment index out of range

In [171]:
center_DF = pd.DataFrame(knn_clust.cluster_centers_, columns = ['x', 'y', 'z'])

In [172]:
center_DF

x         y         z
0    0.785619 -0.058326  0.615148
1    0.058585 -0.738702  0.671299
2   -0.366617  0.844901  0.389266
3    0.839613  0.541949  0.032358
4    0.498585 -0.782433 -0.371499
5    0.264657  0.463003  0.845349
6   -0.926575  0.336829 -0.165582
7   -0.385089 -0.736381  0.556130
8    0.634400  0.209187  0.743781
9    0.366629 -0.912774  0.178455
10   0.267107  0.895756  0.354260
11  -0.308608  0.438971  0.843479
12   0.800422  0.414396 -0.432207
13   0.989784  0.055189  0.129354
14  -0.624586  0.411512 -0.663535
15   0.582562  0.544429  0.603333
16  -0.070518 -0.949823  0.303964
17  -0.306414  0.942170 -0.130647
18   0.121278 -0.880576  0.457933
19  -0.381741 -0.593401  0.708502
20   0.768300 -0.633184 -0.089882
21   0.586153 -0.072367  0.806785
22  -0.412623  0.637449  0.650312
23   0.269177 -0.633217 -0.725440
24  -0.098287 -0.833670  0.543282
25   0.207663 -0.727027  0.654415
26   0.221988  0.816978  0.531253
27   0.179202 -0.975991 -0.120432
28   0.801571  0.137333  0.581471
29   0.965067 -0.092726  0.242744
..        ...       ...       ...
510 -0.952226  0.290919  0.092905
511  0.857160  0.514637 -0.009695
512  0.732130  0.198588  0.651329
513  0.951506 -0.150002  0.267256
514  0.873635  0.028532  0.484831
515  0.370974 -0.923126  0.097333
516  0.924609  0.341192 -0.167264
517 -0.250353  0.945189  0.208841
518 -0.641974  0.731821 -0.228506
519  0.100546 -0.767957  0.632369
520 -0.117770  0.901452  0.415633
521 -0.464726  0.789909  0.399833
522  0.314090  0.839659  0.441571
523 -0.409097 -0.638313  0.651723
524  0.604004  0.506145  0.615084
525  0.612433  0.154527  0.774828
526  0.323476  0.733802  0.596800
527 -0.432366  0.779294  0.453100
528  0.931734  0.110424  0.344110
529  0.432917  0.225978  0.872221
530 -0.688639  0.131824 -0.712761
531  0.954331  0.254939  0.152953
532 -0.131730 -0.887944  0.440355
533  0.668547  0.653583 -0.354234
534 -0.086206 -0.748117  0.657779
535  0.756449  0.632571 -0.164500
536 -0.407624  0.692415  0.594966
537  0.341306  0.459030  0.819958
538  0.121315  0.873424  0.471211
539  0.246762 -0.676931  0.693296

[540 rows x 3 columns]

In [173]:
cluster_distances = gp.dist_mat(center_DF, rowinds = range(20))

array([[    0.        ,  6659.27787507, 10639.73895779, ...,
         4643.33329407,  7840.37050966,  5417.53085592],
       [    0.        ,     0.        , 12532.73768746, ...,
         8527.1759049 , 12105.86849019,  1273.08194815],
       [    0.        ,     0.        ,     0.        , ...,
         6054.83261137,  3194.12217951, 12589.85202375],
       ...,
       [    0.        ,     0.        ,     0.        , ...,
         8592.73643851,  4845.34856976, 15966.83414095],
       [    0.        ,     0.        ,     0.        , ...,
         9935.68010971, 13644.25826444,  2150.49455357],
       [    0.        ,     0.        ,     0.        , ...,
         8873.38130918, 11501.83676044,  4116.06043459]])

In [187]:
fooarray = np.where(((cluster_distances[0,:] < 1) & (cluster_distances[1,:] > 0.5)))[0]

In [186]:
fooarr = np.array([])


False

In [188]:
fooarray

array([  3,   5,   8,  13,  15,  20,  21,  28,  29,  31,  32,  35,  38,
        49,  50,  51,  53,  58,  64,  66,  67,  69,  72,  78,  79,  81,
        89,  92,  93,  97, 100, 101, 103, 104, 105, 114, 116, 119, 124,
       128, 131, 134, 137, 139, 140, 141, 145, 152, 154, 155, 157, 161,
       164, 169, 171, 172, 173, 176, 186, 189, 190, 192, 193, 200, 201,
       202, 204, 205, 210, 212, 215, 216, 218, 219, 220, 224, 229, 230,
       231, 233, 237, 238, 246, 247, 248, 251, 253, 258, 260, 262, 265,
       274, 277, 279, 282, 283, 288, 300, 304, 308, 311, 315, 316, 325,
       327, 328, 334, 335, 339, 341, 343, 347, 351, 354, 357, 358, 359,
       361, 364, 368, 370, 373, 377, 378, 381, 382, 383, 387, 389, 396,
       400, 401, 402, 403, 405, 412, 414, 418, 426, 433, 434, 437, 439,
       440, 443, 448, 449, 454, 455, 456, 460, 462, 465, 466, 469, 471,
       472, 474, 475, 477, 479, 481, 482, 485, 490, 494, 495, 497, 499,
       501, 505, 511, 512, 513, 514, 516, 524, 525, 526, 528, 52

In [196]:
fooarray2 = fooarray.astype(np.float64)

In [198]:
fooarray2[fooarray == 99999] = np.Inf

In [204]:
(fooarray2 < np.Inf)

array([ True,  True, False,  True,  True, False,  True, False,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True, False,  True,  True,
       False,  True, False, False,  True,  True,  True,  True, False,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True, False,  True, False,  True,  True,  True, False,  True,
       False,  True,  True, False,  True,  True, False,  True, False,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False,  True,  True, False,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,

In [207]:
fooarray2.argmax()

2

In [206]:
fooarray2

array([  3.,   5.,  inf,  13.,  15.,  inf,  21.,  inf,  29.,  31.,  inf,
        35.,  38.,  49.,  50.,  51.,  53.,  58.,  inf,  66.,  67.,  69.,
        inf,  78.,  79.,  81.,  89.,  inf,  93.,  97.,  inf, 101., 103.,
        inf, 105., 114.,  inf, 119.,  inf,  inf, 131., 134., 137., 139.,
        inf, 141., 145.,  inf, 154., 155., 157., 161.,  inf, 169., 171.,
        inf, 173.,  inf, 186., 189., 190.,  inf, 193.,  inf, 201., 202.,
        inf, 205., 210.,  inf, 215.,  inf, 218., 219.,  inf,  inf, 229.,
       230., 231., 233., 237., 238., 246., 247.,  inf, 251., 253., 258.,
        inf, 262., 265., 274., 277., 279., 282., 283.,  inf,  inf,  inf,
        inf, 311., 315.,  inf, 325., 327.,  inf, 334., 335., 339., 341.,
       343., 347., 351., 354., 357., 358., 359., 361.,  inf,  inf, 370.,
       373., 377., 378., 381., 382., 383., 387., 389.,  inf,  inf, 401.,
       402., 403., 405.,  inf, 414., 418., 426., 433., 434., 437., 439.,
        inf, 443.,  inf, 449., 454., 455.,  inf,  i